config/routes.rb
Mobile::Application.routes.draw do
  resources :customers
  resources :pages

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :pages, :dependent => :destroy
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])
    
    session[:current_customer] = @customer.id
    
    # Breadcrumb as array of hashes [{:url => "", :text => ""}, ...]
    @breadcrumb = [{:url => customer_path(@customer), :text => @customer.name}]

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to(@customer, :notice => 'Der Kunde wurde erstellt.') }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(@customer, :notice => 'Der Kunde wurde aktualisiert.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(:back, :notice => 'Der Kunde wurde geloescht.') }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.xml
  # def index
  #   @pages = Page.all
  # 
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.xml  { render :xml => @pages }
  #   end
  # en

  # GET /pages/1
  # GET /pages/1.xml
  def show
    @page = Page.find(params[:id])
    
    @customer = Customer.find(session[:current_customer])
    @breadcrumb = [{:url => customer_path(@customer), :text => @customer.name}, {:url => page_path(@page), :text => @page.title}]

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.xml
  def create
    @customer = Customer.find(session[:current_customer])
    @page = @customer.pages.create(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to(@page, :notice => 'Die Seite wurde erstellt.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to(@page, :notice => 'Die Seite wurde aktualisiert.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to(:back, :notice => 'Die Seite wurde geloescht.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<!-- 100% Box Grid Container: Start -->
<div class="grid_24">

	<!-- Box Header: Start -->
	<div class="box_top">
		
		<h2 class="icon users">Kunden</h2>
		
		<%= link_to 'Neuer Kunde', new_customer_path, :class => "button right" %>
		
	</div>
	<!-- Box Header: End -->
	
	<!-- Box Content: Start -->
	<div class="box_content">
	
		<!-- News Table Tabs: Start -->
		<div class="tabs">
		
			<!-- News Sorting Table: Start -->
			<div id="listing">
				
				<table class="sorting">
					<thead>
						<tr>
							<th class="align_left">Name</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center tools">Werkzeuge</th>
						</tr>
					</thead>
					<tbody>
						
						<% @customers.each do |customer| %>
						<tr>
							<td class="align_left"><%= link_to customer.name, customer %></td>
							<td class="align_left center">fdsa</td>
							<td class="align_left center">asdf</td>
							<td class="align_left center">asdf</td>
							<td class="align_left center">fdas</td>
							<td class="align_left tools center">
							  <%= link_to 'Anzeigen', customer, :class => "view tip", :title => "Seiten Anzeigen" %>
							  <%= link_to 'Bearbeiten', edit_customer_path(customer), :class => "edit tip", :title => "Kunde Bearbeiten" %>
							  <%= link_to 'L&ouml;schen', customer, :confirm => 'Diesen Kunden wirklich loeschen?', :method => :delete, :class => "delete tip", :title => "Kunde L&ouml;schen" %>
							</td>
						</tr>
						<% end %>
						
					</tbody>
					
				</table>
				
			</div>
			<!-- News Sorting Table: End -->
		
		</div>
		<!-- News Table Tabs: End -->

	</div>
	<!-- Box Content: End -->
	
</div>
<!-- 100% Box Grid Container: End -->

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<!-- 100% Box Grid Container: Start -->
<div class="grid_24">

	<!-- Box Header: Start -->
	<div class="box_top">
		
		<h2 class="icon pages"><%= @customer.name %></h2>
		
		<%= link_to 'Neue Seite', new_page_path, :class => "button right" %>
		
	</div>
	<!-- Box Header: End -->
	
	<!-- Box Content: Start -->
	<div class="box_content">
	
		<!-- News Table Tabs: Start -->
		<div class="tabs">
		
			<!-- News Sorting Table: Start -->
			<div id="listing">
				
				<table class="sorting">
					<thead>
						<tr>
							<th class="align_left">Name</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center">asdf</th>
							<th class="align_left center tools">Werkzeuge</th>
						</tr>
					</thead>
					<tbody>
						
						<% @customer.pages.each do |page| %>
						<tr>
							<td class="align_left"><%= link_to page.title, page %></td>
							<td class="align_left center">fdsa</td>
							<td class="align_left center">asdf</td>
							<td class="align_left center">asdf</td>
							<td class="align_left center">fdas</td>
							<td class="align_left tools center">
							  <%= link_to 'Anzeigen', page, :class => "view tip", :title => "Seite Anzeigen" %>
							  <%= link_to 'Bearbeiten', edit_page_path(page), :class => "edit tip", :title => "Seite Bearbeiten" %>
							  <%= link_to 'L&ouml;schen', page, :confirm => 'Diese Seite wirklich loeschen?', :method => :delete, :class => "delete tip", :title => "Seite L&ouml;schen" %>
							</td>
						</tr>
						<% end %>
						
					</tbody>
					
				</table>
				
			</div>
			<!-- News Sorting Table: End -->
		
		</div>
		<!-- News Table Tabs: End -->

	</div>
	<!-- Box Content: End -->
	
</div>
<!-- 100% Box Grid Container: End -->

app/views/layouts/_breadcrumb.html.erb
<div id="breadcrumb">
	
	<!-- Breadcrumb: Start -->
	<ul class="left">
		<li class="icon users"><%= link_to 'Kunden', customers_path %></li>
		<% unless @breadcrumb.nil? %>
		  <% @breadcrumb.each do |breadcrumb| %>
        <li class="icon point_right"><%= link_to breadcrumb[:text], breadcrumb[:url] %></li>
      <% end %>
    <% end %>
	</ul>
	<!-- Breadcrumb: End -->
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile</title>
  
  <!-- Imports General CSS and jQuery CSS -->
	<link href="/stylesheets/screen.css" rel="stylesheet" media="screen" type="text/css" />
	<link href="/stylesheets/fixed.css" rel="stylesheet" media="screen" type="text/css" />
	
	<!-- IE Stylesheet ie7 - Added in 1.2 -->
	<!--[if lt IE 8]><html lang="en" class="ie7"><![endif]-->
	
	<!-- IE Stylesheet ie8 - Added in 1.1 -->
	<!--[if IE 8 ]><html lang="en" class="ie8"><![endif]-->
	
	<!-- CSS for Theme Styles -->
	<link href="/stylesheets/theme/custom.css" rel="stylesheet" media="screen" type="text/css" />
  
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
  <!-- IE Canvas Fix for Visualize Charts - Added in 1.1 -->
	<!--[if IE]><script type="text/javascript" src="/javascripts/excanvas.js"></script><![endif]-->
	
	<!-- jQuery thats loaded before document ready to prevent flickering - Rest are found at the bottom -->
	<script type="text/javascript" src="/javascripts/jquery.cookie.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.visualize.js"></script>

</head>
<body>

<!-- Start: Page Wrap -->
<div id="wrap" class="container_24">
	
	
	<!-- Header Grid Container: Start -->
	<div class="grid_24">
		
		<!-- User Panel: Start -->
		<div id="userpanel">
			
			<!-- User: Start -->
			<ul id="user" class="dropdown right">
				<li class="topnav">
					<!-- User Name -->
					<a href="#" class="top icon user">Administrator</a>
					
					<!-- User Dropdown Content: Start -->
					<ul class="subnav">  
	            <li><a href="#" class="icon settings">Einstellungen</a></li>
	            <li><a href="#" class="icon lock">Ausloggen</a></li>  
	        </ul>  
	        <!-- User Dropdown Content: End -->
				</li>
			</ul>
			<!-- User: End -->
			
		</div>
		<!-- User Panel: End -->
		
		<!-- Header: Start -->
		<div id="header">
				
			<!-- Logo: Start -->
			<a href="dashboard.html" id="logo">Simplpan - Admin Panel</a>
			<!-- Logo: End -->
			
			<!-- Navigation: Start -->
			<ul id="navigation" class="dropdown">
				<li><a class="settings" href="#">Einstellungen</a></li>	
			</ul>
			<ul id="navigation" class="dropdown">
				<li><a class="users active" href="#">Kunden</a></li>	
			</ul>
			<ul id="navigation" class="dropdown">
				<li><a class="dashboard" href="#">Dashboard</a></li>	
			</ul>
			<!-- Navigation: End -->
			
		</div>
		<!-- Header: End -->
		
		<!-- Breadcrumb Bar: Start -->
		<%= render 'layouts/breadcrumb' %>
		<!-- Breadcrumb Bar: End -->
		
	</div>
	<!-- Header Grid Container: End -->

<%= yield %>

  <!-- Footer Grid: Start -->
  <div class="grid_24">
  
  	<!-- Footer: Start -->
  	<div id="footer">
  		
  		<p class="left">
  			Copyright &#169; 2011 <a href="#">innocube</a>
  		</p>
  		
  		<!-- Footer Icon Navigation: Start -->
  		<ul class="right">
  			<li><a href="#" class="icon dashboard tip" title="Dashboard">Dashboard</a></li>
  			<li><a href="#" class="icon users tip active" title="Kunden">Kunden</a></li>
  			<li><a href="#" class="icon settings tip" title="Einstellungen">Einstellungen</a></li>
  			<li><a href="#" class="icon home tip" title="Nach oben">Home</a></li>
  		</ul>
  		<!--Footer Icon Navigation: End -->
  		
  	</div>
  	<!-- Footer: End -->
  	
  </div>
  <!-- Footer Grid: End -->

</div>
<!-- End: Page Wrap -->

	<!-- jQuery libs - Rest are found in the head section (at top) -->
	<script type="text/javascript" src="/javascripts/jquery.visualize-tooltip.js"></script>
	<script type="text/javascript" src="/javascripts/jquery-animate-css-rotate-scale.js"></script>
	<script type="text/javascript" src="/javascripts/jquery-ui-1.8.13.custom.min.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.poshytip.min.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.quicksand.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.facebox.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.uniform.min.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.wysiwyg.js"></script>
	<script type="text/javascript" src="/javascripts/syntaxHighlighter/shCore.js"></script>
	<script type="text/javascript" src="/javascripts/syntaxHighlighter/shBrushXml.js"></script>
	<script type="text/javascript" src="/javascripts/syntaxHighlighter/shBrushJScript.js"></script>
	<script type="text/javascript" src="/javascripts/syntaxHighlighter/shBrushCss.js"></script>
	<script type="text/javascript" src="/javascripts/syntaxHighlighter/shBrushPhp.js"></script>
	<script type="text/javascript" src="/javascripts/fileTree/jqueryFileTree.js"></script> <!-- Added in 1.2 -->
	
	<!-- jQuery Customization -->
	<script type="text/javascript" src="/javascripts/custom.js"></script>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @page.title %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>